framework:
    cache:
        # Utilisation de Redis pour le cache d'application
        app: cache.adapter.redis
        default_redis_provider: "%env(REDIS_URL)%"
        pools:
            # Vous pouvez définir des pools de cache spécifiques
            my.dedicated.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
